// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Payroll.Shared.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EmployeeDeviceLock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("employee_device_locks", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Payroll.Shared.AttendanceLog", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("logid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LogID"));

                    b.Property<string>("BiometricID")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("biometricid");

                    b.Property<string>("DeviceID")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("EmployeeID")
                        .HasColumnType("integer")
                        .HasColumnName("employeeid");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_approved");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<string>("LogType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<DateTime>("PunchTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("punchtime");

                    b.HasKey("LogID");

                    b.ToTable("attendancelogs");
                });

            modelBuilder.Entity("Payroll.Shared.BonusRecord", b =>
                {
                    b.Property<int>("BonusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("bonusid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BonusID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<DateTime>("BonusDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("bonus_date");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("integer")
                        .HasColumnName("employeeid");

                    b.Property<int?>("PayrollID_Paid")
                        .HasColumnType("integer")
                        .HasColumnName("payrollid_paid");

                    b.HasKey("BonusID");

                    b.ToTable("bonus_records");
                });

            modelBuilder.Entity("Payroll.Shared.Data.AttendanceRegularization", b =>
                {
                    b.Property<int>("RegularizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("regularization_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RegularizationId"));

                    b.Property<string>("AdminRemarks")
                        .HasColumnType("text")
                        .HasColumnName("admin_remarks");

                    b.Property<string>("ApprovedById")
                        .HasColumnType("text")
                        .HasColumnName("approved_by_id");

                    b.Property<DateOnly>("DateOfPunch")
                        .HasColumnType("date")
                        .HasColumnName("date_of_punch");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<bool>("IsInPunch")
                        .HasColumnType("boolean")
                        .HasColumnName("is_in_punch");

                    b.Property<TimeOnly>("PunchTimeNew")
                        .HasColumnType("time without time zone")
                        .HasColumnName("punch_time_new");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("submission_date");

                    b.HasKey("RegularizationId");

                    b.ToTable("attendance_regularizations");
                });

            modelBuilder.Entity("Payroll.Shared.Data.AuditLog", b =>
                {
                    b.Property<long>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("logid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("LogID"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action_type");

                    b.Property<string>("Details")
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<string>("EntityID")
                        .HasColumnType("text")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_email");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("LogID");

                    b.ToTable("audit_logs");
                });

            modelBuilder.Entity("Payroll.Shared.Data.CompanyHoliday", b =>
                {
                    b.Property<int>("HolidayID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("holidayid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HolidayID"));

                    b.Property<DateOnly>("HolidayDate")
                        .HasColumnType("date")
                        .HasColumnName("holidaydate");

                    b.Property<string>("HolidayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("holidayname");

                    b.HasKey("HolidayID");

                    b.ToTable("holidays", "public");
                });

            modelBuilder.Entity("Payroll.Shared.Data.CompanySetting", b =>
                {
                    b.Property<int>("SettingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SettingID"));

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("BasicSalaryPercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("basic_salary_percentage");

                    b.Property<string>("CityStatePincode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("EmployeeEsiPercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("EmployeeEsiPercentage");

                    b.Property<decimal>("EmployeePfPercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("EmployeePfPercentage");

                    b.Property<decimal>("EmployerEsiPercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("EmployerEsiPercentage");

                    b.Property<decimal>("EmployerPfPercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("EmployerPfPercentage");

                    b.Property<bool>("EnableEmailNotifications")
                        .HasColumnType("boolean")
                        .HasColumnName("EnableEmailNotifications");

                    b.Property<bool>("EnableLeaveAccrual")
                        .HasColumnType("boolean")
                        .HasColumnName("EnableLeaveAccrual");

                    b.Property<bool>("EnableLeaveManagement")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_leave_management");

                    b.Property<bool>("EnablePfEsiSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("EnablePfEsiSystem");

                    b.Property<bool>("EnableProfessionalTax")
                        .HasColumnType("boolean")
                        .HasColumnName("EnableProfessionalTax");

                    b.Property<bool>("EnableSandwichRule")
                        .HasColumnType("boolean")
                        .HasColumnName("EnableSandwichRule");

                    b.Property<bool>("EnableShiftAllowance")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_shift_allowance");

                    b.Property<bool>("EnableSsl")
                        .HasColumnType("boolean")
                        .HasColumnName("EnableSsl");

                    b.Property<bool>("EnableTdsDeduction")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_tds_deduction");

                    b.Property<int>("EndTimeGraceMinutes")
                        .HasColumnType("integer");

                    b.Property<decimal>("EsiWageLimit")
                        .HasColumnType("numeric")
                        .HasColumnName("EsiWageLimit");

                    b.Property<int>("GeoRadiusMeters")
                        .HasColumnType("integer")
                        .HasColumnName("geo_radius_meters");

                    b.Property<int>("LateGraceMinutes")
                        .HasColumnType("integer");

                    b.Property<decimal>("LeaveAccrualRate")
                        .HasColumnType("numeric")
                        .HasColumnName("LeaveAccrualRate");

                    b.Property<double>("OfficeLatitude")
                        .HasColumnType("double precision")
                        .HasColumnName("office_latitude");

                    b.Property<double>("OfficeLongitude")
                        .HasColumnType("double precision")
                        .HasColumnName("office_longitude");

                    b.Property<string>("SalaryCalculationMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SmtpFromEmail")
                        .HasColumnType("text")
                        .HasColumnName("SmtpFromEmail");

                    b.Property<string>("SmtpHost")
                        .HasColumnType("text")
                        .HasColumnName("SmtpHost");

                    b.Property<string>("SmtpPass")
                        .HasColumnType("text")
                        .HasColumnName("SmtpPass");

                    b.Property<int>("SmtpPort")
                        .HasColumnType("integer")
                        .HasColumnName("SmtpPort");

                    b.Property<string>("SmtpUser")
                        .HasColumnType("text")
                        .HasColumnName("SmtpUser");

                    b.Property<int>("WorkDayCutoffHour")
                        .HasColumnType("integer")
                        .HasColumnName("work_day_cutoff_hour");

                    b.Property<string>("ZktecoIP")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ZktecoMachineNumber")
                        .HasColumnType("integer");

                    b.Property<int>("ZktecoPort")
                        .HasColumnType("integer");

                    b.HasKey("SettingID");

                    b.ToTable("CompanySettings", "public");
                });

            modelBuilder.Entity("Payroll.Shared.Data.DailySummary", b =>
                {
                    b.Property<int>("SummaryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("summaryid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SummaryID"));

                    b.Property<decimal>("EarnedStandardHours")
                        .HasColumnType("numeric")
                        .HasColumnName("earned_standard_hours");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("integer")
                        .HasColumnName("employeeid");

                    b.Property<bool>("IsManualOverride")
                        .HasColumnType("boolean")
                        .HasColumnName("is_manual_override");

                    b.Property<TimeSpan>("ScheduledShiftDuration")
                        .HasColumnType("interval")
                        .HasColumnName("scheduled_shift_duration");

                    b.Property<decimal>("ShiftAllowanceEarned")
                        .HasColumnType("numeric")
                        .HasColumnName("shift_allowance_earned");

                    b.Property<DateOnly>("ShiftDate")
                        .HasColumnType("date")
                        .HasColumnName("shiftdate");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<TimeSpan>("TotalBreakPenalty")
                        .HasColumnType("interval")
                        .HasColumnName("total_break_penalty");

                    b.Property<TimeSpan>("TotalLateness")
                        .HasColumnType("interval")
                        .HasColumnName("total_lateness");

                    b.Property<TimeSpan>("TotalOvertimeDuration")
                        .HasColumnType("interval")
                        .HasColumnName("total_overtime_duration");

                    b.Property<TimeSpan>("TotalPenaltyDuration")
                        .HasColumnType("interval")
                        .HasColumnName("total_penalty_duration");

                    b.HasKey("SummaryID");

                    b.ToTable("daily_summaries");
                });

            modelBuilder.Entity("Payroll.Shared.Data.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("employeeid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmployeeID"));

                    b.Property<string>("AspNetUserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("AspNetUserId");

                    b.Property<string>("BankAccountNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("bank_account_number");

                    b.Property<string>("BankIfscCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("bank_ifsc_code");

                    b.Property<string>("BankName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("bank_name");

                    b.Property<decimal>("BasicSalaryComponent")
                        .HasColumnType("numeric")
                        .HasColumnName("basic_salary_component");

                    b.Property<string>("BiometricID")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("biometricid");

                    b.Property<int?>("CompOffDayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("comp_off_day");

                    b.Property<int>("CurrentShiftIndex")
                        .HasColumnType("integer")
                        .HasColumnName("current_shift_index");

                    b.Property<DateOnly?>("DOB")
                        .HasColumnType("date")
                        .HasColumnName("dob");

                    b.Property<decimal>("DaComponent")
                        .HasColumnType("numeric")
                        .HasColumnName("da_component");

                    b.Property<decimal?>("DirectHourlyWage")
                        .HasColumnType("numeric")
                        .HasColumnName("DirectHourlyWage");

                    b.Property<string>("ESINumber")
                        .HasColumnType("text")
                        .HasColumnName("esi_number");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("Email");

                    b.Property<bool>("EnableESI")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_esi");

                    b.Property<bool>("EnablePF")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_pf");

                    b.Property<bool>("EnableShiftRotation")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_shift_rotation");

                    b.Property<DateOnly?>("HireDate")
                        .HasColumnType("date")
                        .HasColumnName("HireDate");

                    b.Property<decimal>("HraComponent")
                        .HasColumnType("numeric")
                        .HasColumnName("hra_component");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateOnly?>("LastRotatedDate")
                        .HasColumnType("date")
                        .HasColumnName("last_rotated_date");

                    b.Property<decimal>("MonthlySalary")
                        .HasColumnType("numeric")
                        .HasColumnName("monthlysalary");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("NightShiftAllowance")
                        .HasColumnType("numeric")
                        .HasColumnName("NightShiftAllowance");

                    b.Property<decimal>("OT_FlatRate")
                        .HasColumnType("numeric")
                        .HasColumnName("ot_flatrate");

                    b.Property<string>("OT_Rule")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ot_rule");

                    b.Property<decimal>("PaidLeaveBalance")
                        .HasColumnType("numeric")
                        .HasColumnName("PaidLeaveBalance");

                    b.Property<string>("PayrollTypeOverride")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("payroll_type_override");

                    b.Property<string>("Role")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("role");

                    b.Property<string>("RotationGroup")
                        .HasColumnType("text")
                        .HasColumnName("rotation_group");

                    b.Property<string>("SalaryCalculationMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("SalaryCalculationMethod");

                    b.Property<TimeOnly?>("ShiftEndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("shiftendtime");

                    b.Property<string>("ShiftRotationPattern")
                        .HasColumnType("text")
                        .HasColumnName("shift_rotation_pattern");

                    b.Property<TimeOnly?>("ShiftStartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("shiftstarttime");

                    b.Property<decimal>("SickLeaveBalance")
                        .HasColumnType("numeric")
                        .HasColumnName("SickLeaveBalance");

                    b.Property<int>("StandardBreakMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("standardbreakminutes");

                    b.Property<int>("StandardHours")
                        .HasColumnType("integer")
                        .HasColumnName("standardhours");

                    b.Property<decimal>("TdsRatePercent")
                        .HasColumnType("numeric")
                        .HasColumnName("tds_rate_percent");

                    b.Property<DateOnly?>("TerminationDate")
                        .HasColumnType("date")
                        .HasColumnName("TerminationDate");

                    b.Property<string>("UAN")
                        .HasColumnType("text")
                        .HasColumnName("uan_number");

                    b.HasKey("EmployeeID");

                    b.ToTable("employees", "public");
                });

            modelBuilder.Entity("Payroll.Shared.Data.EmployeeGpsSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double?>("AverageAccuracyMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("average_accuracy_meters");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<string>("EndReason")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("end_reason");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("ended_at_utc");

                    b.Property<double?>("LastAccuracyMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("last_accuracy_meters");

                    b.Property<int?>("LastAllowedRadiusMeters")
                        .HasColumnType("integer")
                        .HasColumnName("last_allowed_radius_meters");

                    b.Property<double?>("LastDistanceFromOfficeMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("last_distance_from_office_meters");

                    b.Property<bool?>("LastIsWithinAllowedRadius")
                        .HasColumnType("boolean")
                        .HasColumnName("last_is_within_allowed_radius");

                    b.Property<double?>("LastLatitude")
                        .HasColumnType("double precision")
                        .HasColumnName("last_latitude");

                    b.Property<double?>("LastLongitude")
                        .HasColumnType("double precision")
                        .HasColumnName("last_longitude");

                    b.Property<DateTime>("LastUpdateAtUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_update_at_utc");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<double>("TotalDistanceMeters")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0)
                        .HasColumnName("total_distance_meters");

                    b.Property<int>("TotalPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_points");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.HasIndex("EmployeeId", "EndedAtUtc");

                    b.HasIndex("EmployeeId", "StartedAtUtc");

                    b.ToTable("employee_gps_sessions", (string)null);
                });

            modelBuilder.Entity("Payroll.Shared.Data.EmployeeLocationHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("AccuracyMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("accuracy_meters");

                    b.Property<int>("AllowedRadiusMeters")
                        .HasColumnType("integer");

                    b.Property<double>("DistanceFromOfficeMeters")
                        .HasColumnType("double precision");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsWithinAllowedRadius")
                        .HasColumnType("boolean");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CaptureSource")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("capture_source")
                        .HasDefaultValue("Online");

                    b.Property<DateTime>("CapturedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("captured_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("SyncBatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_batch_id");

                    b.Property<DateTime?>("SyncedAtUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("synced_at_utc");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "RecordedAtUtc");

                    b.HasIndex("SessionId", "RecordedAtUtc");

                    b.HasIndex("EmployeeId", "CaptureSource", "CapturedAtUtc");

                    b.HasIndex("SyncBatchId");

                    b.ToTable("employee_location_history", (string)null);
                });

            modelBuilder.Entity("Payroll.Shared.Data.FBPComponent", b =>
                {
                    b.Property<int>("ComponentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("component_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ComponentId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsTaxExempt")
                        .HasColumnType("boolean")
                        .HasColumnName("is_tax_exempt");

                    b.Property<decimal>("MaxAnnualLimit")
                        .HasColumnType("numeric")
                        .HasColumnName("max_annual_limit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("ComponentId");

                    b.ToTable("fbp_components");
                });

            modelBuilder.Entity("Payroll.Shared.Data.FeatureSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AdminCanEditSettings")
                        .HasColumnType("boolean")
                        .HasColumnName("admin_can_edit_settings");

                    b.Property<bool>("AdminCanManageEmployeePermissions")
                        .HasColumnType("boolean")
                        .HasColumnName("admin_can_manage_employee_permissions");

                    b.Property<bool>("AdminCanManageEmployees")
                        .HasColumnType("boolean")
                        .HasColumnName("admin_can_manage_employees");

                    b.Property<bool>("AdminCanManagePunchApprovals")
                        .HasColumnType("boolean")
                        .HasColumnName("admin_can_manage_punch_approvals");

                    b.Property<bool>("AdminCanManageShifts")
                        .HasColumnType("boolean")
                        .HasColumnName("admin_can_manage_shifts");

                    b.Property<bool>("AdminCanRunPayroll")
                        .HasColumnType("boolean")
                        .HasColumnName("admin_can_run_payroll");

                    b.Property<bool>("AdminCanViewAttendance")
                        .HasColumnType("boolean")
                        .HasColumnName("admin_can_view_attendance");

                    b.Property<bool>("AdminCanViewDashboard")
                        .HasColumnType("boolean")
                        .HasColumnName("admin_can_view_dashboard");

                    b.Property<bool>("AdminCanViewReports")
                        .HasColumnType("boolean")
                        .HasColumnName("admin_can_view_reports");

                    b.Property<bool>("EmployeeCanViewAdvance")
                        .HasColumnType("boolean")
                        .HasColumnName("employee_can_view_advance");

                    b.Property<bool>("EmployeeCanViewAttendance")
                        .HasColumnType("boolean")
                        .HasColumnName("employee_can_view_attendance");

                    b.Property<bool>("EmployeeCanViewBonus")
                        .HasColumnType("boolean")
                        .HasColumnName("employee_can_view_bonus");

                    b.Property<bool>("EmployeeCanViewDashboard")
                        .HasColumnType("boolean")
                        .HasColumnName("employee_can_view_dashboard");

                    b.Property<bool>("EmployeeCanViewLeave")
                        .HasColumnType("boolean")
                        .HasColumnName("employee_can_view_leave");

                    b.Property<bool>("EmployeeCanViewLeaveHistory")
                        .HasColumnType("boolean")
                        .HasColumnName("employee_can_view_leave_history");

                    b.Property<bool>("EmployeeCanViewPayslip")
                        .HasColumnType("boolean")
                        .HasColumnName("employee_can_view_payslip");

                    b.Property<bool>("EmployeeCanViewReports")
                        .HasColumnType("boolean")
                        .HasColumnName("employee_can_view_reports");

                    b.Property<bool>("EmployeeCanViewResignation")
                        .HasColumnType("boolean")
                        .HasColumnName("employee_can_view_resignation");

                    b.Property<bool>("EmployeeCanViewShifts")
                        .HasColumnType("boolean")
                        .HasColumnName("employee_can_view_shifts");

                    b.Property<bool>("EmployeeCanViewTax")
                        .HasColumnType("boolean")
                        .HasColumnName("employee_can_view_tax");

                    b.Property<bool>("EmployeeToolsVisible")
                        .HasColumnType("boolean")
                        .HasColumnName("employee_tools_visible");

                    b.Property<bool>("EnableAuditLog")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_audit_log");

                    b.Property<bool>("EnableAutoShiftRotation")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_auto_shift_rotation");

                    b.Property<bool>("EnableBonusManagement")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_bonus_management");

                    b.Property<bool>("EnableCompanyReports")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_company_reports");

                    b.Property<bool>("EnableCustomReporting")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_custom_reporting");

                    b.Property<bool>("EnableEmailNotifications")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_email_notifications");

                    b.Property<bool>("EnableEmployeeManagement")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_employee_management");

                    b.Property<bool>("EnableFlexibleBenefits")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_flexible_benefits");

                    b.Property<bool>("EnableGeoFencing")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_geo_fencing");

                    b.Property<bool>("EnableDualAttendance")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_dual_attendance");

                    b.Property<bool>("EnableAutomaticGeofencePunching")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_automatic_geofence_punching");

                    b.Property<bool>("EnableInAppNotifications")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_in_app_notifications");

                    b.Property<bool>("EnableLeaveAccrual")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_leave_accrual");

                    b.Property<bool>("EnableLeaveManagement")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_leave_management");

                    b.Property<bool>("EnablePayroll")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_payroll");

                    b.Property<bool>("EnableProfessionalTax")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_professional_tax");

                    b.Property<bool>("EnablePunchCorrection")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_punch_correction");

                    b.Property<bool>("EnableRecycleBin")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_recycle_bin");

                    b.Property<bool>("EnableRegularizationRequest")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_regularization_req");

                    b.Property<bool>("EnableResignationModule")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_resignation_module");

                    b.Property<bool>("EnableSalaryAdvance")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_salary_advance");

                    b.Property<bool>("EnableSalaryStructuring")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_salary_structuring");

                    b.Property<bool>("EnableSandwichRule")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_sandwich_rule");

                    b.Property<bool>("EnableShiftAllowance")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_shift_allowance");

                    b.Property<bool>("EnableShiftScheduling")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_shift_scheduling");

                    b.Property<bool>("EnableStatutoryCompliance")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_statutory_compliance");

                    b.Property<bool>("EnableTaxDeclarations")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_tax_declarations");

                    b.Property<bool>("EnableTdsDeduction")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_tds_deduction");

                    b.Property<bool>("EnableYearEndSummary")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_year_end_summary");

                    b.Property<bool>("ShowThemeToggle")
                        .HasColumnType("boolean")
                        .HasColumnName("show_theme_toggle");

                    b.HasKey("Id");

                    b.ToTable("feature_settings");
                });

            modelBuilder.Entity("Payroll.Shared.Data.FlexibleBenefitDeclaration", b =>
                {
                    b.Property<int>("DeclarationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("declaration_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DeclarationId"));

                    b.Property<string>("AdminRemarks")
                        .HasColumnType("text")
                        .HasColumnName("admin_remarks");

                    b.Property<decimal>("AnnualAllocatedAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("annual_allocated_amount");

                    b.Property<string>("ComponentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("component_name");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<int>("FinancialYear")
                        .HasColumnType("integer")
                        .HasColumnName("financial_year");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal>("MonthlyAllocatedAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("monthly_allocated_amount");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("submission_date");

                    b.HasKey("DeclarationId");

                    b.ToTable("flexible_benefit_declarations");
                });

            modelBuilder.Entity("Payroll.Shared.Data.FnFSettlement", b =>
                {
                    b.Property<int>("SettlementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("settlement_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SettlementId"));

                    b.Property<decimal>("AssetRecoveryCost")
                        .HasColumnType("numeric")
                        .HasColumnName("asset_recovery_cost");

                    b.Property<decimal>("BonusPayable")
                        .HasColumnType("numeric")
                        .HasColumnName("bonus_payable");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<decimal>("Gratuity")
                        .HasColumnType("numeric")
                        .HasColumnName("gratuity_amount");

                    b.Property<bool>("IsFinalized")
                        .HasColumnType("boolean")
                        .HasColumnName("is_finalized");

                    b.Property<decimal>("LeaveEncashment")
                        .HasColumnType("numeric")
                        .HasColumnName("leave_encashment_amount");

                    b.Property<decimal>("NetPayable")
                        .HasColumnType("numeric")
                        .HasColumnName("net_payable");

                    b.Property<decimal>("NoticePeriodRecovery")
                        .HasColumnType("numeric")
                        .HasColumnName("notice_period_recovery");

                    b.Property<decimal>("OutstandingAdvances")
                        .HasColumnType("numeric")
                        .HasColumnName("outstanding_advances");

                    b.Property<string>("PaymentReference")
                        .HasColumnType("text")
                        .HasColumnName("payment_reference");

                    b.Property<int>("ResignationRequestId")
                        .HasColumnType("integer")
                        .HasColumnName("resignation_request_id");

                    b.Property<DateTime>("SettlementDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("settlement_date");

                    b.Property<decimal>("UnpaidSalary")
                        .HasColumnType("numeric")
                        .HasColumnName("unpaid_salary");

                    b.HasKey("SettlementId");

                    b.ToTable("fnf_settlements");
                });

            modelBuilder.Entity("Payroll.Shared.Data.GeoPunchAudit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("AccuracyMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("accuracy_meters");

                    b.Property<int>("AllowedRadiusMeters")
                        .HasColumnType("integer")
                        .HasColumnName("allowed_radius_meters");

                    b.Property<long?>("AttendanceLogId")
                        .HasColumnType("bigint")
                        .HasColumnName("attendance_log_id");

                    b.Property<double>("DistanceFromOfficeMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("distance_from_office_meters");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<bool>("IsWithinAllowedRadius")
                        .HasColumnType("boolean")
                        .HasColumnName("is_within_allowed_radius");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<DateTime>("PunchTimeUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("punch_time_utc");

                    b.Property<string>("ResultMessage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("result_message");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("source");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.HasKey("Id");

                    b.ToTable("geo_punch_audits");
                });

            modelBuilder.Entity("Payroll.Shared.Data.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("notification_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("url");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("NotificationId");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("Payroll.Shared.Data.ProfessionalTaxSlab", b =>
                {
                    b.Property<int>("SlabID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("slab_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SlabID"));

                    b.Property<decimal>("MaxSalary")
                        .HasColumnType("numeric")
                        .HasColumnName("max_salary");

                    b.Property<decimal>("MinSalary")
                        .HasColumnType("numeric")
                        .HasColumnName("min_salary");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("tax_amount");

                    b.HasKey("SlabID");

                    b.ToTable("professional_tax_slabs");
                });

            modelBuilder.Entity("Payroll.Shared.Data.ReportDefinition", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("report_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReportId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("ReportName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("report_name");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("report_type");

                    b.Property<string>("TargetRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("target_role");

                    b.HasKey("ReportId");

                    b.ToTable("report_definitions");
                });

            modelBuilder.Entity("Payroll.Shared.Data.ResignationRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("request_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RequestId"));

                    b.Property<string>("AdminRemarks")
                        .HasColumnType("text")
                        .HasColumnName("admin_remarks");

                    b.Property<DateOnly?>("ApprovedLastWorkingDay")
                        .HasColumnType("date")
                        .HasColumnName("approved_last_working_day");

                    b.Property<DateOnly>("DesiredLastWorkingDay")
                        .HasColumnType("date")
                        .HasColumnName("desired_last_working_day");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<bool>("IsSettled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_settled");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("submission_date");

                    b.HasKey("RequestId");

                    b.ToTable("resignation_requests");
                });

            modelBuilder.Entity("Payroll.Shared.Data.TaxDeclaration", b =>
                {
                    b.Property<int>("DeclarationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("declaration_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DeclarationId"));

                    b.Property<string>("AdminRemarks")
                        .HasColumnType("text")
                        .HasColumnName("admin_remarks");

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("approval_date");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<int>("FinancialYear")
                        .HasColumnType("integer")
                        .HasColumnName("financial_year");

                    b.Property<decimal>("HraRentPaid")
                        .HasColumnType("numeric")
                        .HasColumnName("hra_rent_paid");

                    b.Property<decimal>("OtherExemptions")
                        .HasColumnType("numeric")
                        .HasColumnName("other_exemptions");

                    b.Property<string>("Regime")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("regime");

                    b.Property<decimal>("Section80C")
                        .HasColumnType("numeric")
                        .HasColumnName("section_80c");

                    b.Property<decimal>("Section80D")
                        .HasColumnType("numeric")
                        .HasColumnName("section_80d");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("submission_date");

                    b.HasKey("DeclarationId");

                    b.ToTable("tax_declarations");
                });

            modelBuilder.Entity("Payroll.Shared.Data.YearEndSummary", b =>
                {
                    b.Property<int>("SummaryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("summary_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SummaryID"));

                    b.Property<int>("EmployeeID")
                        .HasColumnType("integer")
                        .HasColumnName("employeeid");

                    b.Property<decimal>("GrossTaxableSalary")
                        .HasColumnType("numeric")
                        .HasColumnName("gross_taxable_salary");

                    b.Property<int>("TaxYear")
                        .HasColumnType("integer")
                        .HasColumnName("tax_year");

                    b.Property<int>("TotalAnnualAbsentDays")
                        .HasColumnType("integer")
                        .HasColumnName("total_annual_absent_days");

                    b.Property<decimal>("TotalAnnualOtPay")
                        .HasColumnType("numeric")
                        .HasColumnName("total_annual_ot_pay");

                    b.Property<decimal>("TotalPfContributionEmployee")
                        .HasColumnType("numeric")
                        .HasColumnName("total_pf_contribution_employee");

                    b.Property<decimal>("TotalTdsDeducted")
                        .HasColumnType("numeric")
                        .HasColumnName("total_tds_deducted");

                    b.HasKey("SummaryID");

                    b.ToTable("year_end_summaries");
                });

            modelBuilder.Entity("Payroll.Shared.LeaveRequest", b =>
                {
                    b.Property<int>("LeaveRequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("leaverequestid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LeaveRequestID"));

                    b.Property<int>("EmployeeID")
                        .HasColumnType("integer")
                        .HasColumnName("employeeid");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean")
                        .HasColumnName("isapproved");

                    b.Property<bool>("IsHalfDay")
                        .HasColumnType("boolean")
                        .HasColumnName("is_half_day");

                    b.Property<DateTime?>("LeaveDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("leavedate");

                    b.Property<string>("LeaveType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("leavetype");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.HasKey("LeaveRequestID");

                    b.ToTable("leaverequests");
                });

            modelBuilder.Entity("Payroll.Shared.PayrollHistory", b =>
                {
                    b.Property<int>("PayrollID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("payrollid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PayrollID"));

                    b.Property<int>("AbsentDays")
                        .HasColumnType("integer")
                        .HasColumnName("absentdays");

                    b.Property<decimal?>("BaseSalary")
                        .HasColumnType("numeric")
                        .HasColumnName("basesalary");

                    b.Property<decimal>("BasicComponent")
                        .HasColumnType("numeric")
                        .HasColumnName("basic_salary_component");

                    b.Property<decimal?>("Bonus")
                        .HasColumnType("numeric")
                        .HasColumnName("Bonus");

                    b.Property<decimal?>("Deductions_Advance")
                        .HasColumnType("numeric")
                        .HasColumnName("deductions_advance");

                    b.Property<decimal?>("Deductions_Hours")
                        .HasColumnType("numeric")
                        .HasColumnName("deductions_hours");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("integer")
                        .HasColumnName("employeeid");

                    b.Property<decimal>("EmployerEsiContribution")
                        .HasColumnType("numeric")
                        .HasColumnName("employer_esi_contribution");

                    b.Property<decimal>("EmployerPfContribution")
                        .HasColumnType("numeric")
                        .HasColumnName("employer_pf_contribution");

                    b.Property<decimal>("EsiDeduction")
                        .HasColumnType("numeric")
                        .HasColumnName("esi_deduction");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("numeric")
                        .HasColumnName("HourlyRate");

                    b.Property<int>("ManualLeaveDays")
                        .HasColumnType("integer")
                        .HasColumnName("manualleavedays");

                    b.Property<decimal>("NetSalary")
                        .HasColumnType("numeric")
                        .HasColumnName("netsalary");

                    b.Property<decimal?>("OvertimePay")
                        .HasColumnType("numeric")
                        .HasColumnName("overtimepay");

                    b.Property<int>("PayMonth")
                        .HasColumnType("integer")
                        .HasColumnName("paymonth");

                    b.Property<int>("PayYear")
                        .HasColumnType("integer")
                        .HasColumnName("payyear");

                    b.Property<decimal>("PfDeduction")
                        .HasColumnType("numeric")
                        .HasColumnName("pf_deduction");

                    b.Property<decimal>("PtDeduction")
                        .HasColumnType("numeric")
                        .HasColumnName("pt_deduction");

                    b.Property<TimeSpan?>("ScheduledShiftDuration")
                        .HasColumnType("interval");

                    b.Property<decimal>("TdsDeduction")
                        .HasColumnType("numeric")
                        .HasColumnName("tds_deduction");

                    b.Property<TimeSpan?>("TotalBreakPenalty")
                        .HasColumnType("interval");

                    b.Property<decimal?>("TotalHoursWorked")
                        .HasColumnType("numeric")
                        .HasColumnName("totalhoursworked");

                    b.Property<TimeSpan?>("TotalLateness")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("TotalOvertimeDuration")
                        .HasColumnType("interval")
                        .HasColumnName("totalovertimeduration");

                    b.Property<TimeSpan>("TotalPenaltyDuration")
                        .HasColumnType("interval")
                        .HasColumnName("totalpenaltyduration");

                    b.Property<decimal>("TotalShiftAllowance")
                        .HasColumnType("numeric")
                        .HasColumnName("TotalShiftAllowance");

                    b.HasKey("PayrollID");

                    b.ToTable("payrollhistory");
                });

            modelBuilder.Entity("Payroll.Shared.SalaryAdvance", b =>
                {
                    b.Property<int>("AdvanceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("advanceid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AdvanceID"));

                    b.Property<DateTime?>("AdvanceDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("advancedate");

                    b.Property<string>("AdvanceType")
                        .HasColumnType("text")
                        .HasColumnName("advancetype");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("integer")
                        .HasColumnName("employeeid");

                    b.Property<int?>("PayrollID_Paid")
                        .HasColumnType("integer")
                        .HasColumnName("payrollid_paid");

                    b.HasKey("AdvanceID");

                    b.ToTable("salaryadvances");
                });

            modelBuilder.Entity("Payroll.Shared.ShiftSchedule", b =>
                {
                    b.Property<int>("ScheduleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("scheduleid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ScheduleID"));

                    b.Property<int>("AppliesToDayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("applies_to_day_of_week");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("integer")
                        .HasColumnName("employeeid");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("endtime");

                    b.Property<bool>("IsRecurringPattern")
                        .HasColumnType("boolean")
                        .HasColumnName("is_recurring_pattern");

                    b.Property<int>("PatternDurationDays")
                        .HasColumnType("integer")
                        .HasColumnName("pattern_duration_days");

                    b.Property<DateOnly>("ShiftDate")
                        .HasColumnType("date")
                        .HasColumnName("shiftdate");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("starttime");

                    b.HasKey("ScheduleID");

                    b.ToTable("shiftschedules");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
